version: '3.8'

services:
  # Xero MCP Server
  xero-mcp:
    image: node:18-alpine
    container_name: xero-mcp-server
    ports:
      - "3002:3002"
    environment:
      - XERO_BEARER_TOKEN=${XERO_ACCESS_TOKEN}
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
      - MCP_PORT=3002
    volumes:
      - ./xero-cache:/app/cache
    working_dir: /app
    restart: unless-stopped
    command: >
      sh -c "
        npm init -y &&
        npx -y @xeroapi/xero-mcp-server@latest
      "
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/health" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s
    networks:
      - mcp-network

  # Notion MCP Server
  notion-mcp:
    image: node:18-slim
    container_name: notion-mcp-server
    ports:
      - "3001:3001"
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NODE_ENV=production
      - MCP_PORT=3001
    volumes:
      - ./notion-cache:/app/cache
    working_dir: /app
    restart: unless-stopped
    command: >
      sh -c "
        npm init -y &&
        npx -y @ramidecodes/mcp-server-notion
      "
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mcp-network

  # MCP Gateway/Router (optional - for unified access)
  mcp-gateway:
    image: node:18-alpine
    container_name: mcp-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - XERO_MCP_URL=http://xero-mcp:3002
      - NOTION_MCP_URL=http://notion-mcp:3001
    working_dir: /app
    restart: unless-stopped
    command: >
      sh -c "
        npm init -y &&
        npm install express cors &&
        node -e \"
        const express = require('express');
        const app = express();
        app.use(express.json());
        app.use(require('cors')());
        
        app.get('/health', (req, res) => res.json({
          status: 'healthy',
          services: {
            xero: process.env.XERO_MCP_URL,
            notion: process.env.NOTION_MCP_URL
          }
        }));
        
        app.listen(3000, () => console.log('MCP Gateway running on port 3000'));
        \"
      "
    depends_on:
      - xero-mcp
      - notion-mcp
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
    name: braid-mcp-network

volumes:
  xero-cache:
  notion-cache: