
services:
  agent:
    build:
      context: ./.build
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./credentials:/app/credentials
    # Uncomment the following lines if your agent needs to be interactive
    # stdin_open: true
    # tty: true
