apiVersion: v1
kind: Namespace
metadata:
  name: mcp-servers
  labels:
    name: mcp-servers

---
apiVersion: v1
kind: Secret
metadata:
  name: mcp-secrets
  namespace: mcp-servers
type: Opaque
stringData:
  perplexity-api-key: ""  # Add your actual key
  xero-access-token: ""   # Add your actual token
  xero-client-id: ""      # Add your actual client ID
  xero-client-secret: ""  # Add your actual client secret
  notion-api-key: ""      # Add your actual key

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perplexity-mcp
  namespace: mcp-servers
  labels:
    app: perplexity-mcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: perplexity-mcp
  template:
    metadata:
      labels:
        app: perplexity-mcp
    spec:
      containers:
      - name: perplexity-mcp
        image: your-registry/perplexity-mcp:latest
        ports:
        - containerPort: 3001
        env:
        - name: PERPLEXITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: perplexity-api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: perplexity-mcp-service
  namespace: mcp-servers
spec:
  selector:
    app: perplexity-mcp
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xero-mcp
  namespace: mcp-servers
  labels:
    app: xero-mcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xero-mcp
  template:
    metadata:
      labels:
        app: xero-mcp
    spec:
      containers:
      - name: xero-mcp
        image: your-registry/xero-mcp:latest
        ports:
        - containerPort: 3002
        env:
        - name: XERO_CLIENT_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: xero-access-token
        - name: XERO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: xero-client-id
        - name: XERO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: xero-client-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: xero-mcp-service
  namespace: mcp-servers
spec:
  selector:
    app: xero-mcp
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notion-mcp
  namespace: mcp-servers
  labels:
    app: notion-mcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notion-mcp
  template:
    metadata:
      labels:
        app: notion-mcp
    spec:
      containers:
      - name: notion-mcp
        image: your-registry/notion-mcp:latest
        ports:
        - containerPort: 3003
        env:
        - name: NOTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: notion-api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: notion-mcp-service
  namespace: mcp-servers
spec:
  selector:
    app: notion-mcp
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP

---
# Horizontal Pod Autoscaler for scaling based on CPU/Memory
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: perplexity-mcp-hpa
  namespace: mcp-servers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: perplexity-mcp
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xero-mcp-hpa
  namespace: mcp-servers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xero-mcp
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notion-mcp-hpa
  namespace: mcp-servers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notion-mcp
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80